-- Spirit Life Missions Team — Supabase admin/auth setup
-- Run this in Supabase SQL Editor after creating your project.
-- IMPORTANT: never put the service_role/secret key in the website.

create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  role text not null default 'admin' check (role = 'admin'),
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admins can read own admin record" on public.admin_users;
create policy "admins can read own admin record" on public.admin_users
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "users can insert their own first admin record" on public.admin_users;
create policy "users can insert their own first admin record" on public.admin_users
for insert to authenticated with check (auth.uid() = user_id);

-- Optional hardening: after the first administrator is created, disable
-- public sign-ups in Supabase Authentication settings.
